all:
	latexmk -pdf example.tex

clean:
	latexmk -c
	rm -f *.aux
	rm -f *.bbl
	rm -f *.etd
	rm -f *.fdb_latexmk
	rm -f *.fls
	rm -f *.loa
	rm -f *.log
	rm -f *.lol
	rm -f *.pyg
	rm -f *.run.xml
	rm -f *.stp
	rm -f *.xdv
	rm -rf ./_minted*
