---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  nix:
    uses: ./.github/workflows/nix.yml
  build:
    uses: ./.github/workflows/build.yml
  all:
    needs: [nix, build]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
